# Generated by Django 3.0.3 on 2020-02-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=300)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('published', models.DateTimeField()),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('views', models.IntegerField(blank=True, default=0)),
                ('tags', models.ManyToManyField(to='tags.Tag')),
            ],
        ),
    ]
